### ISSUE TITLE
multisite support?

### ISSUE THREAD

**Issue by johnfelipe** [smartcatdev/support-system#105]

**Comment by smartcatdev** [comment]
@johnfelipe 
have not tested on multi-site yet, however that's something on our list forsure. 

Have you used the plugin yet ? do you have any comments or feedback ?

**Comment by johnfelipe** [comment]
@smartcatdev i need cheatsheet for installation in ubuntu, nginx, php7. wordpress 4.x, can u share me, pls

**Comment by smartcatdev** [comment]
@johnfelipe 
You can download the zip of the stable release from here:
https://downloads.wordpress.org/plugin/ucare-support-system.1.0.1.zip

Alternatively, you can download the dev version here: 
https://github.com/smartcatdev/support-system/archive/master.zip

To install on your server you can do it in one of two ways:

1. in your WP dashboard, go to Plugins - Add New - Upload - Select the zip file. Install and activate.
2. Unpack the zip file, and upload the unpacked folder directly to the plugins folder via FTP
