### ISSUE TITLE
When creating a new ticket, including HTML in any 2 fields causes a JS error

### ISSUE THREAD

**Issue by zackmitchell** [smartcatdev/support-system#110]
To replicate:

- Create a new ticket as a user
- Select a Product
- Of the three fields: Receipt, Subject, Description, if at least two of the fields have HTML content, the ticket will not submit and a JavaScript error is thrown.

![screen shot 2017-04-10 at 1 56 11 pm](https://cloud.githubusercontent.com/assets/12202533/24875019/a8d095aa-1df4-11e7-8213-44d23fd9cac4.png)

**Comment by smartcat-ericgreen** [comment]
HTML needs to be stripped from the title field and receipt ID as well
