### ISSUE TITLE
As code can only be included in a ticket response using <code></code> tags, we should let users know this.

### ISSUE THREAD

**Issue by zackmitchell** [smartcatdev/support-system#111]
Currently if I include an HTML snippet in a response as a user, it simply strips the HTML. We need either an informative notice somewhere that lets users know they have to wrap code in `<code></code>` tags, or, if possible, some kind of validation that will detect HTML in the response when they click submit and popup a notice recommending they wrap the code in `<code></code>` tags.

**Comment by smartcatdev** [comment]
resolved
