### ISSUE TITLE
As a Support Admin or I do not see images attached by Support Users. As a WordPress Admin, I do.

### ISSUE THREAD

**Issue by itssamh** [smartcatdev/support-system#117]

**Comment by itssamh** [comment]
Bilal is able to see images attached to tickets. Sam and Zack were not until their user status was updated from Support Admin to WordPress Admin. 
As a Support User, I am able to see attachments that I have added.

**Comment by smartcatdev** [comment]
@smartcat-ericgreen 
This ticket is important, seems to be issues with image permissions
