### ISSUE TITLE
As a product marketer, I want to know what to create a definitive name, description and tag line (or two) for this product. 

### ISSUE THREAD

**Issue by itssamh** [smartcatdev/support-system#119]

**Comment by itssamh** [comment]
These should appear in the logo, on the website, and be used consistently in facebook and twitter sharing.

**Comment by smartcatdev** [comment]
@itssamh 
uCare Help Desk

**Comment by smartcatdev** [comment]
@zackmitchell 
Please update the Logo for uCare to say *uCare Help Desk*
