### ISSUE TITLE
Move refresh button to more accessible place 

### ISSUE THREAD

**Issue by smartcat-ericgreen** [smartcatdev/support-system#127]
![image](https://cloud.githubusercontent.com/assets/20322777/24962622/6c07f6e6-1f6a-11e7-9158-838f909c040e.png)

**Comment by smartcatdev** [comment]
this isn't currently an error @smartcat-ericgreen 
![image](https://cloud.githubusercontent.com/assets/3696057/24963164/d0e691ac-1f6b-11e7-814d-afc9c9c0133f.png)

**Comment by smartcat-ericgreen** [comment]
More of just a visual thing, not necessity though

**Comment by smartcat-ericgreen** [comment]
Actually if it auto refreshes there isn't a need for the button

**Comment by smartcatdev** [comment]
if you're testing make sure u use the feature/125 branch
