### ISSUE TITLE
Preview in areas where markdown is supported

### ISSUE THREAD

**Issue by ericgreen-dev** [smartcatdev/support-system#133]
Add tab to allow users to preview their html 

![image](https://cloud.githubusercontent.com/assets/20322777/24972190/81d67c22-1f88-11e7-9678-5ab0e1d67585.png)

**Comment by smartcat-ericgreen** [comment]
Remove this from comment panel header
![image](https://cloud.githubusercontent.com/assets/20322777/24972223/a4805ffe-1f88-11e7-9d1c-2892140ff18f.png)
