### ISSUE TITLE
Nav items remain left and right justified on mobile

### ISSUE THREAD

**Issue by ericgreen-dev** [smartcatdev/support-system#141]
These may look better justified the same side

![image](https://cloud.githubusercontent.com/assets/20322777/25018743/1e18ca04-2056-11e7-9cfb-0f4bacf17e1f.png)

![image](https://cloud.githubusercontent.com/assets/20322777/25018814/64bf6d50-2056-11e7-9248-e0536f58f063.png)

**Comment by smartcat-ericgreen** [comment]
Maybe even hide the clock on mobile it isn't really nessary
