### ISSUE TITLE
Ticket list items are cut off with long product names or subjects

### ISSUE THREAD

**Issue by smartcat-ericgreen** [smartcatdev/support-system#142]
![image](https://cloud.githubusercontent.com/assets/20322777/25018869/8f8908f2-2056-11e7-8889-427aabaf34e4.png)

**Comment by smartcatdev** [comment]
Fixed
![image](https://cloud.githubusercontent.com/assets/3696057/25067680/34131df4-2219-11e7-9932-42ac3526ec92.png)
