### ISSUE TITLE
Comments counter broken on edge

### ISSUE THREAD

**Issue by ericgreen-dev** [smartcatdev/support-system#143]
![image](https://cloud.githubusercontent.com/assets/20322777/25018946/deba66c8-2056-11e7-942c-b31c42658547.png)

occurs on firefox developer edition as well 
![image](https://cloud.githubusercontent.com/assets/20322777/25019002/0b5b7320-2057-11e7-9254-1c3450e1601d.png)

**Comment by smartcatdev** [comment]
Looks good in Safari, Firefox & chrome
