### ISSUE TITLE
Need to know when/by whom a ticket was closed

### ISSUE THREAD

**Issue by smartcatdev** [smartcatdev/support-system#160]
Does the system currently store any meta that relates to the closing of a ticket ? 

if no:
- [ ] Create post meta & store timestamp of when a ticket status becomes *closed*
- [ ] Create post meta & store the user ID of the person who closed the ticket

Business logic:
The data above will be used in later iterations of the plugin, so we can dig into metrics by team, agent, month etc..

**Comment by smartcat-ericgreen** [comment]
Maybe also display it in the ticket's status area as well for quick reference

**Comment by smartcat-ericgreen** [comment]
It does not currently store that info
