### ISSUE TITLE
As a support agent, when I try to search for an email address that is not registered, I'm taken to a Blog reel for the site with a "Hello World" post at the top.

### ISSUE THREAD

**Issue by itssamh** [smartcatdev/support-system#175]
![screenshot 2017-05-04 at 10 03 11 am](https://cloud.githubusercontent.com/assets/16105162/25707275/0295dad6-30b1-11e7-95c4-7149ee02b3e1.png)

**Comment by ericgreen-dev** [comment]
It does work when you click 'apply filters' however, I think that it would be more user friendly to capture the enter key after a filter field has been made dirty to submit the form via ajax

**Comment by tkintenn** [comment]
this may have been fixed already but I just installed the plugin in 4.8.1, it doesn't happen to me. However i set my static front page to the support page created by the plugin.
