### ISSUE TITLE
Allow users to upload other types of files 

### ISSUE THREAD

**Issue by ericgreen-dev** [smartcatdev/support-system#206]
- [x] Create setting in Settings allowing user to enter string of allowed file types
- [x] populate with defaults( csv,zip,png,jpg,jpeg)
- [x] update dropzone and php to allow these types

**Comment by smartcatdev** [comment]
Currently the Media section only displays images - an update to the sidebar will allow it to display other types of attached media

**Comment by smartcatdev** [comment]
request for .xls and .rar file support.
