### ISSUE TITLE
When I fresh-install 1.3.0 - Agent notification emails are not available

### ISSUE THREAD

**Issue by smartcatdev** [smartcatdev/support-system#218]
![image](https://user-images.githubusercontent.com/3696057/27564178-064b7c5e-5aa4-11e7-912c-13504666313d.png)

**Comment by smartcatdev** [comment]
![image](https://user-images.githubusercontent.com/3696057/27564183-11223488-5aa4-11e7-8ee5-77349f5b3160.png)

**Comment by ericgreen-dev** [comment]
i'm not experiencing this on a fresh install just pulled from master

**Comment by smartcatdev** [comment]
ill test again

**Comment by smartcatdev** [comment]
weird .. worked this time 👍

**Comment by smartcatdev** [comment]
not an issue
