### ISSUE TITLE
Translating the plugin

### ISSUE THREAD

**Issue by Vyrgo** [smartcatdev/support-system#221]
I tried manually with Poedit on Ubuntu and with Loco Translate directly inside the wordpress backend, but in every case, a large part of the strings can't be found.
![translate-ucare](https://user-images.githubusercontent.com/29736010/27600324-dfed14c8-5b6b-11e7-99ae-aa49b0f1ce80.png)

**Comment by smartcatdev** [comment]
@Vyrgo thanks for posting this - using PoEdit you should be able to retrieve all the translation strings from the provided .pot file within the languages folder. I am not familiar with Loco Translate, however if I use poedit to translate, I can see it picks up 435 strings for translation, which can be saved as an .mo/.po file

![image](https://user-images.githubusercontent.com/3696057/27603197-62891590-5b43-11e7-81b7-ba69a84c474f.png)

![image](https://user-images.githubusercontent.com/3696057/27603581-828f75ea-5b44-11e7-851b-88caf32787c6.png)

Let me know if this helps at all.

**Comment by Vyrgo** [comment]
Well, that's exactly what i did but i  made a little mistake when naming the PO file, everything work perfectly, sorry to have bothered you and thank you for your support, maybe i can contribute with my translation when that will be finished?

**Comment by smartcatdev** [comment]
glad you got it working ! 
yes you can definitely contribute your translation when ready ! feel free to comment in this ticket again and provide the translated file or you can fork and publish the update 

best regards

**Comment by Vyrgo** [comment]
I almost finished the french translation, but if we could have an option to change the date format and sentence to explain it... for exemple: in french we do no use "Ago", only "since *date* " and the format is dd-mm-yy.

Thank you, this plugin perfectly fit my needs :+1:

**Comment by smartcatdev** [comment]
thanks for the suggestion, will consider that in the updates!

**Comment by Vyrgo** [comment]
Here we are
[ucare-fr_FR.zip](https://github.com/smartcatdev/support-system/files/1106707/ucare-fr_FR.zip)

**Comment by smartcatdev** [comment]
thank you! this will be added to the next version of the plugin. we can add your name in the readme file as the author of the french translation if you like, just comment with your name and/or wordpress username/website if you like.

thank you

**Comment by Vyrgo** [comment]
You're welcome.
Sure, you can add me, my name is Philippe Chiorboli and my company website is https://www.guerni.fr/
Have a nice day.

**Comment by smartcatdev** [comment]
great! ill add your info in the readme file of the next update

**Comment by chicohaager** [comment]
Hi,
just translated this great plugin into german language.
Here we go 
[ucare-de_DE.zip](https://github.com/smartcatdev/support-system/files/1601099/ucare-de_DE.zip)
Best regards from Germany

**Comment by smartcatdev** [comment]
thanks @chicohaager !
I will add your translations to the plugin in the next update.
Do you want to feature your name/website in the plugin readme ? if you want, we can add your info,

**Comment by chicohaager** [comment]
Sure, you can add me, my name is HolgerKuehn and my company website is https://virtual-services.info/
Cheers
