### ISSUE TITLE
WPML compatibility

### ISSUE THREAD

**Issue by mywebstuff** [smartcatdev/support-system#238]
Hi!
Loving your plugin so much! I just want to ask you if a WPML compatibility is even achievable somehow with this plugin or if it's not then is it on the horizon?

Thanks for your reply and the plugin itself!

**Comment by smartcatdev** [comment]
@mjanos10  thank you for your comments! 
We're looking into adding polylang/wpml compatibility to the plugin in future updates forsure. This might be part of version 1.4.0 or later.

Please take a minute to leave the plugin a rating on WordPress: https://wordpress.org/support/plugin/ucare-support-system/reviews/

We would really appreciate it!

thank you
