### ISSUE TITLE
Suggestion: Removal of footer brand link for any paid add-ons

### ISSUE THREAD

**Issue by beeing** [smartcatdev/support-system#251]
Hi, as above, you should add in the option of removal of the hardcoded footer link to encourage adoption to your commercial add-ons.

**Comment by smartcatdev** [comment]
Hi @beeing 

We're working on something to this effect right now. 

Thank you for the recommendation!

**Comment by smartcatdev** [comment]
hi again @beeing 

the Pro bundle includes the option to remove any branding from the plugin
![image](https://user-images.githubusercontent.com/3696057/33436568-6f06aa68-d5b3-11e7-82f5-063cc8c31110.png)

**Comment by smartcatdev** [comment]
https://ucaresupport.com/downloads/ucare-pro/
