### ISSUE TITLE
apply_filters on post_content

### ISSUE THREAD

**Issue by cfrazier** [smartcatdev/support-system#298]
Content from tickets could / should be processed with 'the_content' filter before sending email notifications.

`'ticket_content' => apply_filters( 'the_content', $ticket->post_content )`

After receiving quite a number of complex support requests that required formatting on the content, it became clear that I would need to fork and add the filter to make the notifications useful. My fork is here: 

https://bitbucket.org/managedword/mw-support-system/

**Comment by smartcatdev** [comment]
Thank you for that! Can you give an example of some issues this helped you solve ?

So to create a pull request and have it properly attributed to your account, please follow these instructions:

https://help.github.com/articles/creating-a-pull-request-from-a-fork/
Once we receive the PR it will be reviewed and merged into master when the next update is rolled out.

If you're not too concerned with that let us know, we'll just download your repo and copy over your changes.

**Comment by cfrazier** [comment]
Figured I'd file a pull request, just for fun.

As far as issues... I had a request come in via email with a bunch of JSON debug code in it. Because the notifications weren't adding new lines, the whole thing ended up unreadable from the email sent, which was bad.

Actually, it's mostly issues that stem from email piping, since that's how our users tend to interact with support. We were seeing signature blocks showing up in the main text of the report, which was just a mess. Of course, the same emails were going out to our users and they thought it was an error.

The filter trick is super simple and doesn't add any overhead. Hopefully it helps!

Excellent work!

**Comment by ericgreen-dev** [comment]
@cfrazier I have created an issue for this (#317) and we will investigate ways of improving the default formatting in a future release
