### ISSUE TITLE
Improve the UX of the Login/Register form

### ISSUE THREAD

**Issue by erikgeurts** [smartcatdev/support-system#332]
I think the login form is confusing for people who first come to the support system and need to register as a user before being able to create a ticket. Here's what it looks like:
![image](https://user-images.githubusercontent.com/5102461/40218948-b78e20a0-5a73-11e8-880a-5b4e8d66cf50.png)
When I first saw it, it felt like I could either log in with an existing username and password, or enter a new username and password and then click Register.
As it turned out, clicking Register takes me to yet another form where the real signup process starts:
![image](https://user-images.githubusercontent.com/5102461/40218996-ebc1ac48-5a73-11e8-89aa-c151da4fd198.png)
My proposal would be to make the login screen more clear as follows:
- change the Register button from being positioned right next to to Log in button, and move it towards the Forgot password link.
- make the Forgot password link into a real button, and put the Register button right next to that
- give both the Forgot Password and the Register button the same color, and make that a different color from the Login button.
- perhaps even change the wording of the "Register button" to "Sign Up"

Also, I believe there should be some explanation just above the login form and below the logo, informing the visitor where they've ended up, and why they need a username to use the Support system in the first place.

Please let me know if you'd like me to sketch a mockup of the layout of the login form I'm proposing.

**Comment by erikgeurts** [comment]
Please forgive me for the crudeness of this mockup, I'm not an artist. Here is what I had in mind:
![untitled](https://user-images.githubusercontent.com/5102461/40408075-a89b0972-5e66-11e8-9dd6-984adb9b0624.png)
Note that there shouldn't be a pointer over the Register button, that happened by accident when I took the screenshot.

**Comment by smartcatdev** [comment]
Thanks @erikgeurts looks good,

we're gonna work on the UX of this and your mockup is quite helpful.

Best regards

**Comment by erikgeurts** [comment]
Thanks for the update, I'll be keeping a close eye on the new version when it is released!

**Comment by smartcatdev** [comment]
## step 1
** user enters their email address ** applies to both registered and non-registered users
![image](https://user-images.githubusercontent.com/3696057/41369192-335412f0-6f12-11e8-8c84-1747b49b484e.png)

## Step 2
- if first time using the system
![image](https://user-images.githubusercontent.com/3696057/41369240-5a330624-6f12-11e8-8806-dfaaa46571fd.png)
- if returning user
![image](https://user-images.githubusercontent.com/3696057/41369295-7ed7aa66-6f12-11e8-89d1-eae367b34162.png)
## Step 3
user gets taken to the Create Ticket page right away
![image](https://user-images.githubusercontent.com/3696057/41369266-6e859074-6f12-11e8-8fb5-77cede588219.png)

**Comment by smartcatdev** [comment]
We also added Terms of Service, that you can toggle on/off from the settings page.
if you toggle on, user has to accept the terms. The plugin will store a flag in the user meta that the user has accepted the terms.
updating the terms will force users to re-accept terms.

![image](https://user-images.githubusercontent.com/3696057/41369353-a42607cc-6f12-11e8-9ebb-4ad2156609e1.png)

**Comment by smartcatdev** [comment]
If terms of service is toggled on, the terms will show up between step 2 and step 3.

**Comment by erikgeurts** [comment]
Thanks for sharing this. It looks very good, and I don't consider my time spent on that mockup wasted. You took my suggestion and improved upon it which is always good.

The only reservation I have, has to do with the use of password managers in this kind of two-phase signin process. In the interest of security, I tend to use automatically generated, long, very random passwords, that I do not personally remember. Instead, I trust my password manager (or rather, Chrome's smart lock), to remember my password.

In the case of this application, entering the username first and the password next throws of smart lock a bit as you can see in this screenshot:
![image](https://user-images.githubusercontent.com/5102461/41369820-4233de8e-6f46-11e8-8df7-ad45b570b251.png)

Somehow, it is unable to figure out what the username is against which it needs to store that password.

I've seen other applications somehow working around this, I assume by having the username as a hidden field on the screen where we enter the password. Gmail is an example of that I believe.

If it were possible to help users pick safe passwords by enabling the use of a password manager so they're not tempted to use 'secret' or 'abc123', that would be a bonus for everyone involved.

**Comment by smartcatdev** [comment]
oh thats a good point. Ill ahve a look and see.

one more change we did, the system no longer handles passwords for you. By that i mean, no more text passwords delivered by email.

when users do the "forgot pw" option, they will now get a link to reset their own pw. we're gonna be enforcing rules, or allowing admin to use regex or somethin. more to come on that. should take effect with this in 1.7.0/1.7.1

**Comment by smartcatdev** [comment]
sign-in/signup updates deployed in version 1.7.0 along with GDPR compliance tools. 
let us know if you detect any errors in a new ticket!
