### ISSUE TITLE
Disable actions & commenting when ticket is closed

### ISSUE THREAD

**Issue by smartcatdev** [smartcatdev/support-system#52]
- [x] When ticket is resolved or closed, additional commenting needs to be disabled
- [x] Include a default message when commenting is disabled
- [x] add option allowing admin to customize the message that shows when ticket is closed/resolved.

**Comment by smartcatdev** [comment]
@smartcat-ericgreen 
The bug has been resolved, however there's a UX here issue here.

when the ticket is resolved/closed, the comment form is still visible.

### potential fix
- [ ] when the ticket status is updated, if the selected status is *resolved*, reload the ticket tab

**Comment by smartcat-ericgreen** [comment]
Depends on #73
