### ISSUE TITLE
Make modals great again

### ISSUE THREAD

**Issue by smartcat-ericgreen** [smartcatdev/support-system#60]
Maybe square off and enlarge modals to make them more front and center

![image](https://cloud.githubusercontent.com/assets/20322777/22600484/a01cfc0c-ea08-11e6-94bb-726f1599a5c2.png)

**Comment by smartcatdev** [comment]
Progress
![image](https://cloud.githubusercontent.com/assets/3696057/22770324/9e2416d4-ee5d-11e6-9029-74946ebf3fca.png)
