### ISSUE TITLE
Customer Satisfaction Extension

### ISSUE THREAD

**Issue by smartcatdev** [smartcatdev/support-system#80]
When tickets are closed, the customer should receive an email with a question to rate the quality of service they received. The customer can action that by selecting a rating, which will trigger to store the data in a custom table. 

The ratings table and the ticket is a 1 to 1 relationship. This allows later for queries regarding:

1. total client satisfaction ( percentage )
2. number of satisfied customers
3. satisfaction per agent
4. satisfaction for product

and more

**Comment by ericgreen-dev** [comment]
- [ ] create an GUID from the user ID and ticket # 
- [ ] Inject the survey html into the footer action
- [ ] Have a form in the email that triggers an action on the server when submitted
- [ ] Store the results in the database

**Comment by smartcatdev** [comment]
Follow https://github.com/smartcatdev/support-system-customer-satisfaction
