### ISSUE TITLE
Fatal error: get() on Null - possible WPDB scope issue

### ISSUE THREAD

**Issue by smartcatdev** [smartcatdev/support-system#87]
this fatal error is occurring when certain plugins are active. currently the error can be observed when the Dokan plugin is active. this is triggered somewhere within the start() method of the main plugin class, specifically in `config/admin_settings.php` 

please investigate fix in a seperate branch, and PR when completed as this needs to be released as a new version

**Comment by smartcat-ericgreen** [comment]
should be resolved with #89
